In [103]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sb

In [104]:
crdata = pd.read_csv(r"C:\Users\sabar\OneDrive\Documents\AI_ML\Credit Risk Analytics\Risk Dataset\credit_risk_dataset.csv")

In [105]:
crdata.shape

(32581, 12)

In [106]:
crdata_copy = crdata.copy()

In [107]:
crdata_copy.shape

(32581, 12)

In [108]:
crdata.describe()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_cred_hist_length
count,32581.000000,3.258100e+04,31686.000000,32581.000000,29465.000000,32581.000000,32581.000000,32581.000000
mean,27.734600,6.607485e+04,4.789686,9589.371106,11.011695,0.218164,0.170203,5.804211
std,6.348078,6.198312e+04,4.142630,6322.086646,3.240459,0.413006,0.106782,4.055001
min,20.000000,4.000000e+03,0.000000,500.000000,5.420000,0.000000,0.000000,2.000000
25%,23.000000,3.850000e+04,2.000000,5000.000000,7.900000,0.000000,0.090000,3.000000
50%,26.000000,5.500000e+04,4.000000,8000.000000,10.990000,0.000000,0.150000,4.000000
75%,30.000000,7.920000e+04,7.000000,12200.000000,13.470000,0.000000,0.230000,8.000000
max,144.000000,6.000000e+06,123.000000,35000.000000,23.220000,1.000000,0.830000,30.000000

In [109]:
missing_data = crdata.isnull().sum()
missing_data_pct = (missing_data/len(crdata))*100

In [110]:
missing_data_pct.round(2)

person_age                    0.00
person_income                 0.00
person_home_ownership         0.00
person_emp_length             2.75
loan_intent                   0.00
loan_grade                    0.00
loan_amnt                     0.00
loan_int_rate                 9.56
loan_status                   0.00
loan_percent_income           0.00
cb_person_default_on_file     0.00
cb_person_cred_hist_length    0.00
dtype: float64

In [111]:
crdata['person_income'].sort_values(ascending=False)

32297    6000000
30049    2039784
32546    1900000
32497    1782000
31924    1440000
          ...
15961       4800
15963       4200
27896       4200
15964       4080
31930       4000
Name: person_income, Length: 32581, dtype: int64

In [112]:
crdata.loc[(crdata['person_age']<70) & (crdata['person_income']<6000000),['person_age','person_income','person_emp_length','loan_amnt']].groupby(['person_age','person_income','person_emp_length'])['loan_amnt'].agg(
Total_Loan_Amount= 'sum')

In [ ]:
# Filtering and selecting columns using .loc, then grouping
result = crdata.loc[
    (crdata['person_age'] > 70) & (crdata['person_income'] > 6000000), 
    ['person_age', 'person_income', 'person_emp_length', 'loan_amnt']
].groupby(['person_age', 'person_income', 'person_emp_length'])['loan_amnt'].agg(
    Total_Loan_Amount='sum'
).reset_index()

In [ ]:
# Corrected Pandas syntax
result = crdata[
    (crdata['person_age'] <= 70) & (crdata['person_income'] <= 6000000)
].groupby(['person_age', 'person_income', 'person_emp_length'])['loan_amnt'].agg(
    Total_Loan_Amount='sum'
).reset_index()

In [ ]:
result

In [ ]:
crdata['missing_data']=crdata.isnull().sum()

In [ ]:
crdata.shape

In [ ]:
crdata.head()

In [ ]:
crdata.drop(columns=['missing_data'],inplace=True)

In [ ]:
crdata.head()

In [ ]:

threshold = 10

missing_percentage = (crdata.isnull().sum() / len(crdata)) * 100

columns_to_drop = missing_percentage[missing_percentage > threshold].index.tolist()

In [ ]:
'''if columns_to_drop:
    print(f"Dropping columns: {columns_to_drop}")
    crdata = crdata.drop(columns=columns_to_drop)
else:
    print("No columns exceeded the missing data threshold.")'''

In [ ]:
columns_to_drop.count

In [ ]:
crdata['loan_intent'].value_counts()

In [ ]:
crdata

In [ ]:
crdata.pivot_table(index='person_home_ownership',values='person_income',aggfunc=
                   'count').sort_values(by='person_income', ascending=False)

In [ ]:
crdata.pivot_table(index='person_age',columns='loan_status',values='loan_intent', aggfunc=
                    'count').reset_index().sort_values(by='person_age', ascending=False)

In [ ]:
cleaned_df = crdata[crdata['person_age']<=70]

In [ ]:
'''cr_age_remove.pivot_table(index='person_emp_length', values='',aggfunc='count').reset_index().sort_values(by='person_emp_length', ascending=False)'''

In [ ]:
crdata['loan_status'].value_counts()

In [ ]:
crdata.columns.to_list()

In [ ]:
cleaned_df.shape

In [ ]:
#rdata.drop(columns='person_age', inplace=True)

In [ ]:
cleaned_df = cleaned_df[(cleaned_df['person_age']<=90) & (cleaned_df['person_emp_length']<=45)]

In [ ]:
cleaned_df.describe()

In [ ]:
cleaned_df.isnull().sum()

In [ ]:
cleaned_df.fillna({'loan_int_rate':cleaned_df['loan_int_rate'].median()}, inplace=True)

In [ ]:
cleaned_df.isnull().sum()

In [ ]:
cleaned_df.groupby('loan_status').count()['person_age']

In [ ]:
str(6823/(24842+6823)*100)+str('%')

In [ ]:
cleaned_df_copy = cleaned_df.copy()

In [ ]:
cleaned_df_copy.shape

In [ ]:
cleaned_df.shape

In [ ]:
cleaned_df.drop(columns='loan_grade',inplace=True)

In [ ]:
cleaned_df.shape

In [ ]:
cleaned_df.head(3)

In [ ]:
cleaned_df.reset_index(drop=True, inplace=True)

In [ ]:
cleaned_df

#  Categorical Fetures Treatment

In [ ]:
#One hot encoding

In [ ]:
cleaned_df_cft = cleaned_df.copy()

In [ ]:
person_home_ownership = pd.get_dummies(cleaned_df_cft['person_home_ownership'], drop_first=True).astype(int)
loan_intent = pd.get_dummies(cleaned_df_cft['loan_intent'],drop_first=True).astype(int)

In [ ]:
person_home_ownership

In [ ]:
loan_intent

In [113]:
# Binnary feeding

In [114]:
cb_person_default_on_binnary = np.where(cleaned_df_cft['cb_person_default_on_file']=='Y',1,0)
cb_person_default_on_binnary

KeyError: 'cb_person_default_on_file'

In [ ]:
cleaned_df_cft.head(2)

In [ ]:
cleaned_df_cft.drop(columns=['person_home_ownership','loan_intent','cb_person_default_on_file','loan_status'], inplace=True)

In [ ]:
cleaned_df_cft

# Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [ ]:
data_to_scale = cleaned_df_cft.copy()

In [ ]:
scaled_df = scaler.fit_transform(data_to_scale)

In [ ]:
scaled_df

In [ ]:
cleaned_df_cft.columns

In [ ]:
scaled_tran_df=pd.DataFrame(scaled_df, columns=['person_age', 'person_income', 'person_emp_length', 'loan_amnt',
       'loan_int_rate', 'loan_percent_income', 'cb_person_cred_hist_length'])

In [ ]:
scaled_tran_df

In [ ]:
round(scaled_tran_df['person_age'].std(),2)

In [115]:
round(scaled_tran_df['person_income'].mean(),2)

-0.0

In [116]:
scaled_concat_df = pd.concat([scaled_tran_df,person_home_ownership,loan_intent],axis=1)

In [117]:
scaled_concat_df

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,OTHER,OWN,RENT,EDUCATION,HOMEIMPROVEMENT,MEDICAL,PERSONAL,VENTURE
0,-1.090587,-1.078051,0.054432,-1.367192,0.034115,-0.655113,-0.939656,0,1,0,1,0,0,0,0
1,-0.441211,-1.078051,-0.938456,-0.656810,0.597575,3.767461,-0.692664,0,0,0,0,0,1,0,0
2,-0.765899,-0.018803,-0.193790,4.000141,1.366226,3.391072,-0.939656,0,0,1,0,0,1,0,0
3,-0.603555,-0.229137,0.799097,4.000141,1.053554,3.579267,-0.445671,0,0,1,0,0,1,0,0
4,-1.090587,-1.072366,-0.690234,-1.130398,-1.268682,0.756347,-0.939656,0,1,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31666,4.753795,-0.255665,-0.938456,-0.609451,0.692028,-0.561016,5.976124,0,0,0,0,0,0,1,0
31667,4.266764,1.013916,-0.193790,1.257276,-1.154688,-0.184626,3.259210,0,0,0,0,0,0,1,0
31668,6.052547,0.180161,-0.442012,4.000141,-0.014740,2.732391,5.482140,0,0,1,0,1,0,0,0
31669,4.591451,1.582385,0.054432,0.842886,0.144853,-0.655113,4.988155,0,0,0,0,0,0,1,0
31670,6.214891,-0.464104,-0.690234,-0.502893,-0.340439,-0.184626,5.976124,0,0,1,0,0,1,0,0

In [118]:
scaled_concat_df['loan_status']=cleaned_df['loan_status']

In [119]:
scaled_concat_df['cb_person_default_on_file'] = np.where(cleaned_df['cb_person_default_on_file']=='Y',1,0)

In [120]:
scaled_concat_df

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,OTHER,OWN,RENT,EDUCATION,HOMEIMPROVEMENT,MEDICAL,PERSONAL,VENTURE,loan_status,cb_person_default_on_file
0,-1.090587,-1.078051,0.054432,-1.367192,0.034115,-0.655113,-0.939656,0,1,0,1,0,0,0,0,0,0
1,-0.441211,-1.078051,-0.938456,-0.656810,0.597575,3.767461,-0.692664,0,0,0,0,0,1,0,0,1,0
2,-0.765899,-0.018803,-0.193790,4.000141,1.366226,3.391072,-0.939656,0,0,1,0,0,1,0,0,1,0
3,-0.603555,-0.229137,0.799097,4.000141,1.053554,3.579267,-0.445671,0,0,1,0,0,1,0,0,1,1
4,-1.090587,-1.072366,-0.690234,-1.130398,-1.268682,0.756347,-0.939656,0,1,0,0,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31666,4.753795,-0.255665,-0.938456,-0.609451,0.692028,-0.561016,5.976124,0,0,0,0,0,0,1,0,0,0
31667,4.266764,1.013916,-0.193790,1.257276,-1.154688,-0.184626,3.259210,0,0,0,0,0,0,1,0,0,0
31668,6.052547,0.180161,-0.442012,4.000141,-0.014740,2.732391,5.482140,0,0,1,0,1,0,0,0,1,0
31669,4.591451,1.582385,0.054432,0.842886,0.144853,-0.655113,4.988155,0,0,0,0,0,0,1,0,0,0
31670,6.214891,-0.464104,-0.690234,-0.502893,-0.340439,-0.184626,5.976124,0,0,1,0,0,1,0,0,0,0

In [121]:
scaled_concat_df.columns = scaled_concat_df.columns.str.lower()

In [122]:
scaled_concat_df.groupby('loan_status')['education'].count()

loan_status
0    24846
1     6825
Name: education, dtype: int64

In [123]:
     round((6825/(6825+24846))*100,2)

21.55

# SMOTE - Synthetic Minority Oversampling Techinque

## KNN Techinque is used behind the SMOTE technique (K-Nearest Neighbhors)

In [124]:
%pip install imbalanced-learn
from imblearn.over_sampling import SMOTE

Requirement already satisfied: imbalanced-learn in c:\users\sabar\anaconda3\lib\site-packages (0.12.4)
Requirement already satisfied: joblib>=1.1.1 in c:\users\sabar\anaconda3\lib\site-packages (from imbalanced-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\sabar\anaconda3\lib\site-packages (from imbalanced-learn) (2.2.0)
Requirement already satisfied: scipy>=1.5.0 in c:\users\sabar\anaconda3\lib\site-packages (from imbalanced-learn) (1.9.1)
Requirement already satisfied: numpy>=1.17.3 in c:\users\sabar\anaconda3\lib\site-packages (from imbalanced-learn) (1.21.5)
Requirement already satisfied: scikit-learn>=1.0.2 in c:\users\sabar\anaconda3\lib\site-packages (from imbalanced-learn) (1.0.2)
Note: you may need to restart the kernel to use updated packages.

In [125]:
scaled_smote_df = scaled_concat_df.copy()

In [126]:
target = scaled_concat_df['loan_status']
features = scaled_concat_df.drop(columns=['loan_status'], axis=1)

In [127]:
target.shape

(31671,)

In [128]:
features.shape

(31671, 16)

In [129]:
smote=SMOTE()

In [131]:
balanced_features, balanced_target = smote.fit_resample(features,target)

In [132]:
balanced_features.shape

(49692, 16)

In [133]:
balanced_target.shape

(49692,)

In [188]:
balanced_features

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,other,own,rent,education,homeimprovement,medical,personal,venture,cb_person_default_on_file
0,-1.090587,-1.078051,0.054432,-1.367192,0.034115,-0.655113,-0.939656,0,1,0,1,0,0,0,0,0
1,-0.441211,-1.078051,-0.938456,-0.656810,0.597575,3.767461,-0.692664,0,0,0,0,0,1,0,0,0
2,-0.765899,-0.018803,-0.193790,4.000141,1.366226,3.391072,-0.939656,0,0,1,0,0,1,0,0,0
3,-0.603555,-0.229137,0.799097,4.000141,1.053554,3.579267,-0.445671,0,0,1,0,0,1,0,0,1
4,-1.090587,-1.072366,-0.690234,-1.130398,-1.268682,0.756347,-0.939656,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49687,0.102971,-0.257863,-0.777616,-0.151007,2.149996,-0.187266,0.709268,0,0,0,0,0,1,0,0,0
49688,-0.609521,0.004487,0.391475,0.792199,-0.980946,0.158092,-0.445671,0,0,0,0,0,1,0,0,0
49689,0.208165,-0.426726,-1.186678,0.842886,0.279286,1.605802,0.789289,0,0,1,0,0,0,1,0,0
49690,-0.928243,-0.788117,0.302653,-0.131316,-1.339987,1.768533,-0.692664,0,0,1,0,0,1,0,0,0
49691,0.240786,-0.692113,-0.193790,-1.138328,1.481377,-0.739316,-0.198679,0,0,1,0,0,0,0,1,1

In [189]:
balanced_target

0        0
1        1
2        1
3        1
4        1
        ..
49687    1
49688    1
49689    1
49690    1
49691    1
Name: loan_status, Length: 49692, dtype: int64

In [140]:
scaled_smote_df.groupby('loan_status')['education'].count()

loan_status
0    24846
1     6825
Name: education, dtype: int64

In [159]:
balance_check = pd.DataFrame({'target':balanced_target})

In [161]:
balance_check.groupby('target').size()

target
0    24846
1    24846
dtype: int64

# Model Training

In [135]:
%pip install xgboost logisticregression

Requirement already satisfied: xgboost in c:\users\sabar\anaconda3\lib\site-packages (2.1.4)
Collecting logisticregression
  Downloading logisticregression-2025.0.0-py3-none-any.whl (2.0 kB)
Requirement already satisfied: numpy in c:\users\sabar\anaconda3\lib\site-packages (from xgboost) (1.21.5)
Requirement already satisfied: scipy in c:\users\sabar\anaconda3\lib\site-packages (from xgboost) (1.9.1)
Requirement already satisfied: pandas in c:\users\sabar\anaconda3\lib\site-packages (from logisticregression) (1.4.4)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\sabar\appdata\roaming\python\python39\site-packages (from pandas->logisticregression) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\sabar\anaconda3\lib\site-packages (from pandas->logisticregression) (2022.1)
Requirement already satisfied: six>=1.5 in c:\users\sabar\appdata\roaming\python\python39\site-packages (from python-dateutil>=2.8.1->pandas->logisticregression) (1.17.0)
Installing collected packages: logisticregression
Successfully installed logisticregression-2025.0.0
Note: you may need to restart the kernel to use updated packages.

In [169]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [190]:
x_train, x_test, y_train, y_test = train_test_split(balanced_features,balanced_target, test_size=0.20, random_state=42)

In [191]:
x_train.shape

(39753, 16)

In [192]:
y_train.shape

(39753,)

In [193]:
x_test.shape

(9939, 16)

In [194]:
y_test.shape

(9939,)

In [197]:
logit = LogisticRegression()

In [198]:
logit.fit(x_train,y_train)

LogisticRegression()

In [199]:
logit.score(x_train, y_train)

0.7786582144743793

In [200]:
logit.score(x_test, y_test)

0.7799577422275883